name: tecnofit_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  carousel_slider: ^5.0.0

  # State Management
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get: ^4.6.6
  redux: ^5.0.0
  riverpod: ^2.5.1

  # HTTP Client
  http: ^1.2.2  
  # JSON Serialization
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true
